In [2]:
import pandas as pd

In [5]:
ufo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv')

In [17]:
ufo.head()
ufo.columns = ufo.columns.str.replace(' ','_')

In [14]:
ufo.shape

(18241, 5)

In [16]:
booleans = []
for i in ufo.Shape_Reported:
    if i == 'LIGHT':
        booleans.append(True)
    else:
        booleans.append(False)

In [19]:
ufo.head()

                   City Colors_Reported Shape_Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [21]:
booleans[0:5]

[False, False, False, False, True]

In [23]:
len(booleans)

18241

In [25]:
shape_light = pd.Series(booleans)

In [27]:
shape_light.head()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [29]:
ufo[shape_light]##passed in list of bools and will only show bool = 1

,City,Colors_Reported,Shape_Reported,State,Time
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
10,Fontana,NaN,LIGHT,CA,8/15/1937 21:00
22,NaN,NaN,LIGHT,LA,8/15/1943 0:00
54,Cleveland,NaN,LIGHT,OH,6/1/1947 2:30
86,Henrietta,NaN,LIGHT,OK,8/12/1947 1:00
95,Ojai,NaN,LIGHT,CA,7/15/1948 22:00
101,Grays,NaN,LIGHT,SC,5/15/1949 6:30
110,Mill Valley,NaN,LIGHT,CA,8/15/1949 21:00
116,Lackland AFB,NaN,LIGHT,TX,10/10/1949 21:00
137,Florence,NaN,LIGHT,CO,6/30/1950 17:30
139,Bay St. Louis,NaN,LIGHT,MS,7/2/1950 21:00
140,East Palestine,NaN,LIGHT,OH,7/10/1950 20:30
191,Miami,NaN,LIGHT,FL,6/30/1952 9:00
196,Miami,NaN,LIGHT,FL,6/30/1952 21:00
215,Hamilton,NaN,LIGHT,OH,8/15/1952 22:15
247,Vallejo,NaN,LIGHT,CA,8/7/1953 21:00
261,Santa Monica,NaN,LIGHT,CT,1/15/1954 20:00
270,El Cerrito,NaN,LIGHT,CA,6/1/1954 19:00
274,Fish Canyon,NaN,LIGHT,CA,6/1/1954 23:00
278,Palm Beach,NaN,LIGHT,CA,6/15/1954 11:00
286,Hawthorne,NaN,LIGHT,CA,6/30/1954 12:00
297,Bridge Hampton,NaN,LIGHT,NY,7/15/1954 22:00
301,North Hollywood,NaN,LIGHT,CA,8/1/1954 22:00
313,New York City,NaN,LIGHT,NY,2/15/1955 19:00
321,Pensacola,NaN,LIGHT,FL,6/6/1955 1:00
324,Missouri,NaN,LIGHT,MO,6/15/1955 4:30
327,Rantoul,NaN,LIGHT,IL,6/17/1955 7:00
331,Dumas,NaN,LIGHT,TX,6/30/1955 21:00
336,Ringold,NaN,LIGHT,LA,7/15/1955 22:00
339,Madisonville,NaN,LIGHT,KY,8/14/1955 1:00
...,...,...,...,...,...
18095,Mesa,RED,LIGHT,AZ,12/8/2000 19:15
18096,Beaver,NaN,LIGHT,OH,12/8/2000 20:00
18097,Carlsbad,NaN,LIGHT,NM,12/9/2000 18:00
18098,Mesa,NaN,LIGHT,AZ,12/9/2000 19:30
18103,Marshfield,NaN,LIGHT,WI,12/10/2000 15:00
18110,Gilbert,RED,LIGHT,AZ,12/11/2000 23:45
18113,Kittery,NaN,LIGHT,ME,12/12/2000 15:45
18118,Greenville,NaN,LIGHT,NC,12/12/2000 23:30
18121,Redwood Valley,BLUE,LIGHT,CA,12/15/2000 1:09
18122,San Diego,NaN,LIGHT,CA,12/15/2000 4:05
18123,Waldorf,GREEN,LIGHT,MD,12/15/2000 5:30
18134,Graham,GREEN,LIGHT,WA,12/16/2000 0:20
18135,Pioneer,NaN,LIGHT,TN,12/16/2000 0:45
18136,Athens,NaN,LIGHT,TX,12/16/2000 19:00
18143,Bolingbrook,NaN,LIGHT,IL,12/17/2000 19:10
18145,Kennewick,NaN,LIGHT,WA,12/17/2000 20:17
18146,Baton Rouge,NaN,LIGHT,LA,12/17/2000 20:40
18150,Spokane,NaN,LIGHT,WA,12/18/2000 17:00
18153,Show Low,NaN,LIGHT,AZ,12/18/2000 21:20
18158,Woodland,ORANGE,LIGHT,CA,12/19/2000 23:30
18171,Kettleman City,NaN,LIGHT,CA,12/22/2000 3:30
18175,Chandler,NaN,LIGHT,AZ,12/23/2000 19:00
18177,Chandler,RED,LIGHT,AZ,12/23/2000 22:00
18192,Atlanta,ORANGE,LIGHT,GA,12/25/2000 20:30
18200,Imperial,NaN,LIGHT,AZ,12/27/2000 7:00
18201,Santa Paula,NaN,LIGHT,CA,12/27/2000 10:00
18209,Houston,NaN,LIGHT,TX,12/28/2000 17:09
18216,Garden Grove,ORANGE,LIGHT,CA,12/29/2000 16:10
18228,Kingsville,NaN,LIGHT,TX,12/31/2000 4:00
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45

In [33]:
new_light = ufo.Shape_Reported == 'LIGHT'##series compare

In [35]:
new_light.head()

0    False
1    False
2    False
3    False
4     True
Name: Shape_Reported, dtype: bool

In [37]:
ufo[ufo.Shape_Reported == 'LIGHT']##act as a if

,City,Colors_Reported,Shape_Reported,State,Time
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
10,Fontana,NaN,LIGHT,CA,8/15/1937 21:00
22,NaN,NaN,LIGHT,LA,8/15/1943 0:00
54,Cleveland,NaN,LIGHT,OH,6/1/1947 2:30
86,Henrietta,NaN,LIGHT,OK,8/12/1947 1:00
95,Ojai,NaN,LIGHT,CA,7/15/1948 22:00
101,Grays,NaN,LIGHT,SC,5/15/1949 6:30
110,Mill Valley,NaN,LIGHT,CA,8/15/1949 21:00
116,Lackland AFB,NaN,LIGHT,TX,10/10/1949 21:00
137,Florence,NaN,LIGHT,CO,6/30/1950 17:30
139,Bay St. Louis,NaN,LIGHT,MS,7/2/1950 21:00
140,East Palestine,NaN,LIGHT,OH,7/10/1950 20:30
191,Miami,NaN,LIGHT,FL,6/30/1952 9:00
196,Miami,NaN,LIGHT,FL,6/30/1952 21:00
215,Hamilton,NaN,LIGHT,OH,8/15/1952 22:15
247,Vallejo,NaN,LIGHT,CA,8/7/1953 21:00
261,Santa Monica,NaN,LIGHT,CT,1/15/1954 20:00
270,El Cerrito,NaN,LIGHT,CA,6/1/1954 19:00
274,Fish Canyon,NaN,LIGHT,CA,6/1/1954 23:00
278,Palm Beach,NaN,LIGHT,CA,6/15/1954 11:00
286,Hawthorne,NaN,LIGHT,CA,6/30/1954 12:00
297,Bridge Hampton,NaN,LIGHT,NY,7/15/1954 22:00
301,North Hollywood,NaN,LIGHT,CA,8/1/1954 22:00
313,New York City,NaN,LIGHT,NY,2/15/1955 19:00
321,Pensacola,NaN,LIGHT,FL,6/6/1955 1:00
324,Missouri,NaN,LIGHT,MO,6/15/1955 4:30
327,Rantoul,NaN,LIGHT,IL,6/17/1955 7:00
331,Dumas,NaN,LIGHT,TX,6/30/1955 21:00
336,Ringold,NaN,LIGHT,LA,7/15/1955 22:00
339,Madisonville,NaN,LIGHT,KY,8/14/1955 1:00
...,...,...,...,...,...
18095,Mesa,RED,LIGHT,AZ,12/8/2000 19:15
18096,Beaver,NaN,LIGHT,OH,12/8/2000 20:00
18097,Carlsbad,NaN,LIGHT,NM,12/9/2000 18:00
18098,Mesa,NaN,LIGHT,AZ,12/9/2000 19:30
18103,Marshfield,NaN,LIGHT,WI,12/10/2000 15:00
18110,Gilbert,RED,LIGHT,AZ,12/11/2000 23:45
18113,Kittery,NaN,LIGHT,ME,12/12/2000 15:45
18118,Greenville,NaN,LIGHT,NC,12/12/2000 23:30
18121,Redwood Valley,BLUE,LIGHT,CA,12/15/2000 1:09
18122,San Diego,NaN,LIGHT,CA,12/15/2000 4:05
18123,Waldorf,GREEN,LIGHT,MD,12/15/2000 5:30
18134,Graham,GREEN,LIGHT,WA,12/16/2000 0:20
18135,Pioneer,NaN,LIGHT,TN,12/16/2000 0:45
18136,Athens,NaN,LIGHT,TX,12/16/2000 19:00
18143,Bolingbrook,NaN,LIGHT,IL,12/17/2000 19:10
18145,Kennewick,NaN,LIGHT,WA,12/17/2000 20:17
18146,Baton Rouge,NaN,LIGHT,LA,12/17/2000 20:40
18150,Spokane,NaN,LIGHT,WA,12/18/2000 17:00
18153,Show Low,NaN,LIGHT,AZ,12/18/2000 21:20
18158,Woodland,ORANGE,LIGHT,CA,12/19/2000 23:30
18171,Kettleman City,NaN,LIGHT,CA,12/22/2000 3:30
18175,Chandler,NaN,LIGHT,AZ,12/23/2000 19:00
18177,Chandler,RED,LIGHT,AZ,12/23/2000 22:00
18192,Atlanta,ORANGE,LIGHT,GA,12/25/2000 20:30
18200,Imperial,NaN,LIGHT,AZ,12/27/2000 7:00
18201,Santa Paula,NaN,LIGHT,CA,12/27/2000 10:00
18209,Houston,NaN,LIGHT,TX,12/28/2000 17:09
18216,Garden Grove,ORANGE,LIGHT,CA,12/29/2000 16:10
18228,Kingsville,NaN,LIGHT,TX,12/31/2000 4:00
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45

In [43]:
test=ufo[(ufo.Shape_Reported == 'LIGHT')]

In [55]:
test[test.Colors_Reported == 'ORANGE']

                  City Colors_Reported Shape_Reported State              Time
1256       Spartanburg          ORANGE          LIGHT    SC   6/30/1966 21:00
1995           Lansing          ORANGE          LIGHT    MI   7/11/1970 20:30
2214        Texas City          ORANGE          LIGHT    TX    6/1/1972 22:00
2256        Greensboro          ORANGE          LIGHT    NC   6/30/1972 21:00
2429             Perth          ORANGE          LIGHT    NY    7/1/1973 20:00
2659         Gibralter          ORANGE          LIGHT    MI    6/20/1974 1:00
2713    East Berkshire          ORANGE          LIGHT    VT   7/24/1974 21:00
3538       Waitesfield          ORANGE          LIGHT    VT    6/29/1977 3:00
3873             Union          ORANGE          LIGHT    MO   7/26/1978 20:00
3936       Leavenworth          ORANGE          LIGHT    KS    9/2/1978 21:00
6572           Brawley          ORANGE          LIGHT    CA    6/5/1991 17:00
6864       Jerseyville          ORANGE          LIGHT    IL    8/5/1992 23:00
6940          San Jose          ORANGE          LIGHT    IL  11/15/1992 18:30
6967       Gainesville          ORANGE          LIGHT    FL   1/20/1993 18:50
7629          Lu Verne          ORANGE          LIGHT    IA   12/9/1994 20:30
7651       Los Angeles          ORANGE          LIGHT    CA   12/30/1994 2:05
9100   Tehachapi Mtns.          ORANGE          LIGHT    CA    2/24/1996 3:20
9843             Hurst          ORANGE          LIGHT    TX   12/28/1996 1:00
9986         Gila Bend          ORANGE          LIGHT    AZ   3/13/1997 19:45
10003          Phoenix          ORANGE          LIGHT    AZ   3/13/1997 20:15
10068         Maricopa          ORANGE          LIGHT    AZ   3/16/1997 21:00
10107       Cobleskill          ORANGE          LIGHT    NY    3/30/1997 0:45
10220        Las Vegas          ORANGE          LIGHT    NV    5/9/1997 21:00
10330        Coushatta          ORANGE          LIGHT    LA    6/3/1997 23:00
10336          Bothell          ORANGE          LIGHT    WA    6/6/1997 21:45
10417            Ocala          ORANGE          LIGHT    FL    6/20/1997 1:00
10459         Freehold          ORANGE          LIGHT    NJ     7/1/1997 0:00
10635           Tooele          ORANGE          LIGHT    UT   7/23/1997 21:30
10903   Jackson Center          ORANGE          LIGHT    OH  10/28/1997 20:15
10910        Santa Ana          ORANGE          LIGHT    CA  10/31/1997 22:18
...                ...             ...            ...   ...               ...
14162        Flagstaff          ORANGE          LIGHT    AZ   8/12/1999 10:00
14195       Trout Lake          ORANGE          LIGHT    WA   8/14/1999 23:00
14352        Wadsworth          ORANGE          LIGHT    OH     9/1/1999 4:30
14411             Lima          ORANGE          LIGHT    OH    9/1/1999 23:30
14598        Rushville          ORANGE          LIGHT    IL   9/15/1999 21:05
15314         Ashgrove          ORANGE          LIGHT    MO  11/17/1999 22:15
15374        Flagstaff          ORANGE          LIGHT    AZ  11/26/1999 21:30
15489         Michigan          ORANGE          LIGHT    MI  12/13/1999 15:40
15502   Mountain Grove          ORANGE          LIGHT    MO  12/15/1999 19:30
15601         Rockford          ORANGE          LIGHT    IL  12/31/1999 23:30
15923         Ashgrove          ORANGE          LIGHT    MO    2/17/2000 0:00
15967          McClave          ORANGE          LIGHT    CO   2/26/2000 19:20
15981          Antioch          ORANGE          LIGHT    CA   2/29/2000 22:40
16069          Sunland          ORANGE          LIGHT    CA    3/12/2000 1:30
16132      Lake Forest          ORANGE          LIGHT    CA   3/22/2000 20:05
16238          Antioch          ORANGE          LIGHT    CA    4/13/2000 5:30
16287            Magna          ORANGE          LIGHT    UT   4/20/2000 21:23
16326         Lewiston          ORANGE          LIGHT    ME   4/27/2000 13:00
16420        Vacaville          ORANGE          LIGHT    CA   5/13/2000 23:45
16535        Manzanita          ORANGE          LIGHT    OR    6/3/2000 22:00
16644      Willard Bay          ORANGE          LIGHT    UT    6/20/2000 0:00
16690           Orange          ORANGE          LIGHT    CA   6/25/2000 21:23
17301   Goverment Camp          ORANGE          LIGHT    OR   8/26/2000 23:30
17305           Lenexa          ORANGE          LIGHT    KS   8/28/2000 22:15
17716           Eureka          ORANGE          LIGHT    CA  10/17/2000 20:30
17818           Marion          ORANGE          LIGHT    KS  10/29/2000 21:30
18001    Coeur d'Alene          ORANGE          LIGHT    ID  11/22/2000 17:15
18158         Woodland          ORANGE          LIGHT    CA  12/19/2000 23:30
18192          Atlanta          ORANGE          LIGHT    GA  12/25/2000 20:30
18216     Garden Grove          ORANGE          LIGHT    CA  12/29/2000 16:10

[91 rows x 5 columns]