In [2]:
import pandas as pd

In [4]:
ufo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv')

In [6]:
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [8]:
ufo.columns = ufo.columns.str.replace(' ','_')

In [16]:
test=ufo.dropna()
test[(test.Shape_Reported == 'LIGHT') & (test.Colors_Reported =='RED')]

,City,Colors_Reported,Shape_Reported,State,Time
434,Kansas City,RED,LIGHT,MO,7/15/1957 23:30
780,Alexandria,RED,LIGHT,VA,4/20/1963 17:00
1102,Terrebonne,RED,LIGHT,OR,9/15/1965 21:30
1128,Old Saybrook,RED,LIGHT,CT,11/9/1965 17:45
1561,Temple,RED,LIGHT,OK,2/15/1968 19:00
1653,Ponca City,RED,LIGHT,OK,6/30/1968 11:00
2500,Loomis,RED,LIGHT,CA,9/15/1973 23:00
2869,Lodi,RED,LIGHT,OH,5/7/1975 2:00
3396,St. George,RED,LIGHT,UT,10/21/1976 21:00
3446,Louisville,RED,LIGHT,KY,4/1/1977 22:00
3653,Kennewick,RED,LIGHT,WA,10/15/1977 23:00
3673,Malvern,RED,LIGHT,AR,12/15/1977 22:00
3811,Fort Drum,RED,LIGHT,NY,7/1/1978 8:45
3844,Santa Fe,RED,LIGHT,NM,7/15/1978 0:00
3870,St. Robert,RED,LIGHT,MO,7/26/1978 0:00
4379,Fort Mill,RED,LIGHT,SC,7/15/1980 22:00
4425,Atlantic Ocean,RED,LIGHT,NC,9/12/1980 21:00
4451,Manchester,RED,LIGHT,NH,10/10/1980 23:30
4493,Wilmont,RED,LIGHT,MN,1/19/1981 21:30
4547,Morrow,RED,LIGHT,OH,6/15/1981 0:30
5107,Manotowish Waters,RED,LIGHT,WI,8/1/1984 23:00
5127,Medanales,RED,LIGHT,NM,9/1/1984 21:00
5270,Alvordon,RED,LIGHT,OH,6/30/1985 22:00
5560,Pocahontas,RED,LIGHT,AR,12/12/1986 20:00
5613,Island Lake,RED,LIGHT,IL,5/15/1987 23:00
5696,Indianapolis,RED,LIGHT,IN,8/1/1987 0:00
5740,Wytheville,RED,LIGHT,VA,10/8/1987 23:00
5774,Las Vegas,RED,LIGHT,NV,12/20/1987 17:15
6306,Seneca,RED,LIGHT,SC,5/21/1990 20:50
6308,Eugene,RED,LIGHT,OR,5/24/1990 23:00
...,...,...,...,...,...
16890,Gilbert,RED,LIGHT,AZ,7/12/2000 20:00
16897,Glendale,RED,LIGHT,AZ,7/12/2000 20:30
16899,Falfurias,RED,LIGHT,TX,7/12/2000 22:00
16906,Gilbert,RED,LIGHT,AZ,7/13/2000 20:00
16937,Gilbert,RED,LIGHT,AZ,7/15/2000 19:30
16982,Highlands Ranch,RED,LIGHT,CO,7/20/2000 22:00
17011,Chandler,RED,LIGHT,AZ,7/25/2000 20:15
17014,Gilbert,RED,LIGHT,AZ,7/25/2000 20:40
17022,San Diego,RED,LIGHT,CA,7/25/2000 22:00
17033,Gilbert,RED,LIGHT,AZ,7/27/2000 20:15
17077,Key Peninsula,RED,LIGHT,WA,8/2/2000 21:30
17084,Surprise,RED,LIGHT,AZ,8/3/2000 21:00
17092,Springbrook,RED,LIGHT,WI,8/4/2000 3:00
17098,Gilbert,RED,LIGHT,AZ,8/4/2000 20:00
17099,Gilbert,RED,LIGHT,AZ,8/4/2000 20:10
17166,Covina,RED,LIGHT,CA,8/11/2000 23:00
17200,Chandler,RED,LIGHT,AZ,8/15/2000 20:00
17202,Gilbert,RED,LIGHT,AZ,8/15/2000 20:00
17205,Gilbert,RED,LIGHT,AZ,8/15/2000 20:10
17206,Chandler,RED,LIGHT,AZ,8/15/2000 20:14
17208,Gilbert,RED,LIGHT,AZ,8/15/2000 20:15
17565,San Fernando Valley,RED,LIGHT,CA,9/30/2000 21:47
17566,Arleta,RED,LIGHT,CA,9/30/2000 22:00
17811,Gilbert,RED,LIGHT,AZ,10/29/2000 18:30
17878,Ann Arbor,RED,LIGHT,MI,11/4/2000 19:30
17880,Sanibel Island,RED,LIGHT,FL,11/4/2000 22:00
18095,Mesa,RED,LIGHT,AZ,12/8/2000 19:15
18110,Gilbert,RED,LIGHT,AZ,12/11/2000 23:45
18177,Chandler,RED,LIGHT,AZ,12/23/2000 22:00
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45

In [18]:
test[test.Colors_Reported.isin(['RED','WHITE','BLUE'])]

,City,Colors_Reported,Shape_Reported,State,Time
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
19,Bering Sea,RED,OTHER,AK,4/30/1943 23:00
36,Portsmouth,RED,FORMATION,VA,7/10/1945 1:30
82,San Jose,BLUE,CHEVRON,CA,7/15/1947 21:00
84,Modesto,BLUE,DISK,CA,8/8/1947 22:00
91,Scipio,RED,SPHERE,IN,5/10/1948 19:00
152,Irving,BLUE,DISK,KS,4/15/1951 0:30
164,Provo,BLUE,DISK,UT,7/10/1951 23:30
178,Norfolk,RED,FIREBALL,VA,6/1/1952 22:00
226,Cambridge,RED,SPHERE,MA,4/1/1953 18:00
238,Cleveland,RED,FIREBALL,OH,6/30/1953 0:00
288,St. Louis Airport,RED,OVAL,MO,7/1/1954 21:00
289,Los Angeles,RED,CIRCLE,CA,7/1/1954 22:00
304,Beaumont,RED,DISK,TX,9/9/1954 12:30
383,Middle River,BLUE,CIRCLE,MD,9/15/1956 20:00
434,Kansas City,RED,LIGHT,MO,7/15/1957 23:30
513,Perry,RED,TRIANGLE,IA,9/1/1958 21:00
574,Four States,RED,SPHERE,WV,10/16/1959 22:30
630,Watchung,RED,CIGAR,NJ,8/10/1960 18:00
693,Bakersfield,RED,CIRCLE,CA,11/11/1961 23:00
707,Pittsburg,RED,VARIOUS,OK,5/15/1962 21:30
748,Lodi,RED,OTHER,OH,8/8/1962 14:00
780,Alexandria,RED,LIGHT,VA,4/20/1963 17:00
790,Williamsport,RED,OTHER,MD,6/1/1963 8:00
796,Royal Oak,RED,TRIANGLE,MI,6/1/1963 18:00
825,Albert Lea,BLUE,OVAL,MN,7/11/1963 20:00
876,North Yakima,BLUE,CIRCLE,WA,6/1/1964 21:30
879,Montrose,BLUE,LIGHT,CO,6/10/1964 3:00
888,Milan,RED,SPHERE,TN,6/15/1964 21:00
894,Alexandria,RED,DISK,VA,6/28/1964 21:00
...,...,...,...,...,...
17749,Cooper City,BLUE,OTHER,FL,10/22/2000 19:30
17751,Puyallup,RED,DIAMOND,WA,10/22/2000 23:00
17765,Kent,BLUE,OTHER,WA,10/24/2000 6:45
17781,Longville,RED,VARIOUS,LA,10/26/2000 21:30
17787,Phoenix,RED,FIREBALL,AZ,10/27/2000 8:30
17793,Laurel,BLUE,SPHERE,MD,10/28/2000 1:00
17811,Gilbert,RED,LIGHT,AZ,10/29/2000 18:30
17830,Brookfield,RED,OTHER,WI,10/31/2000 18:30
17878,Ann Arbor,RED,LIGHT,MI,11/4/2000 19:30
17880,Sanibel Island,RED,LIGHT,FL,11/4/2000 22:00
17925,Lynchburg,BLUE,LIGHT,VA,11/12/2000 23:15
17984,Arlington,RED,DISK,VA,11/19/2000 22:00
17987,Belfry,BLUE,LIGHT,KY,11/20/2000 3:00
18020,Denver,RED,TRIANGLE,CO,11/24/2000 17:52
18045,Kapa'a,BLUE,CIRCLE,HI,11/30/2000 5:30
18064,Seldon,RED,TRIANGLE,NY,12/2/2000 22:50
18095,Mesa,RED,LIGHT,AZ,12/8/2000 19:15
18110,Gilbert,RED,LIGHT,AZ,12/11/2000 23:45
18121,Redwood Valley,BLUE,LIGHT,CA,12/15/2000 1:09
18129,Beaver,RED,DISK,PA,12/15/2000 18:25
18148,Highland Park,BLUE,VARIOUS,NJ,12/18/2000 2:30
18167,Gilbert,RED,CIRCLE,AZ,12/21/2000 19:05
18170,MM 110,BLUE,CIRCLE,AZ,12/22/2000 3:00
18172,Toomsuba,RED,OVAL,MS,12/23/2000 4:00
18177,Chandler,RED,LIGHT,AZ,12/23/2000 22:00
18191,Fallston,RED,VARIOUS,MD,12/25/2000 19:15
18210,Monument Valley,BLUE,OTHER,UT,12/28/2000 17:51
18220,Shasta Lake,BLUE,DISK,CA,12/29/2000 20:30
18233,Anchorage,RED,VARIOUS,AK,12/31/2000 21:00
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45